version: '3'
services:
  nginx-rtmp:
    build:
      context: .
    container_name: streaming_nginx

    ports:
      - 1935:1935
      - 8080:80

    volumes:
      - "/Volumes/USB DISK/video:/usr/share/nginx/html/video"
      # - "./video:/opt/data/video"
      # - "./dist:/usr/share/nginx/html"